from datetime import datetime
import os

# API_KEY = "d610c594d99e9914f73ea072d3904a8758f107cb"
API_KEY = os.getenv("SERPER_API_KEY")

CIUDADES = ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"]

# Lista base unificada con marcador {ciudad} para insertar la ciudad dinámica
PROMPTS_ROTATIVOS = [
    "taller de música en español {} site:.org OR site:.edu",
    "centro cultural hispano {} talleres musicales mayo junio 2025",
    "colectivo latinoamericano {} canto percusión piano",
    "eventos culturales hispanos {} Australia 2025",
    '"taller de improvisación musical" {} español',
    "workshop música en español {} 2025",
    "actividad reciente centro cultural latino {} junio 2025",
    "asociación cultural hispana {} música",
    '"Spanish music workshop" {} site:eventbrite.com',
    '"Latin American collective" {} percussion 2025',
    "eventos musicales en español {} comunidad latina",
    "concierto participativo español {} colectivo",
    '"taller de canto" español comunidad hispana {}',
    "{} centro cultural hispano actividades musicales recientes",
    "grupos latinos en {} que hacen talleres de música",
    "Spanish cultural association {} recent music events",
    "june 2025 Spanish music classes {}",
    '"Latin music workshop" {} cultural center',
    "{} Spanish choir percussion collective June 2025",
    "talleres latinos de música en español en {} Australia 2025",
    "actividades para familias hispanohablantes con niños en {} junio 2025",
    "talleres culturales para niños migrantes en {} comunidad hispana",
    "centro comunitario latino en {} actividades familiares recientes",
    "eventos para familias latinas con niños en {} mayo junio 2025",
    "programas recreativos en español para niños en {}",
    "educación comunitaria en español {} familias migrantes",
    "iniciativas para padres y niños latinos en {} comunidad hispana",
    "actividades para familias migrantes hispanas en {} 2025",
    "taller de arte o música para niños hispanohablantes en {}",
    "asociaciones culturales latinas en {} actividades infantiles",
    '"Latin family programs" {} site:eventbrite.com',
    '"Spanish community activities for children" {} Australia',
    "programas de integración para niños en español {} 2025",
    "clases de cultura latina para niños en {} comunidad migrante",
    "juegos y actividades educativas en español {} familias latinas",
    "apoyo a familias migrantes hispanas con hijos en {}",
    "eventos recientes para padres latinos en {} Australia",
    "Melbourne comunidad latina actividades recientes para niños",
    "asociaciones hispanohablantes en {} con programas para niños",
    "familias migrantes latinas en {} actividades culturales recientes",
    "clases de español con música para niños en {}",
    "academias que enseñan español con canciones en {}",
    "escuelas hispanohablantes en {} que usan música para enseñar español",
    "cursos de español con canto y ritmo en {}",
    "enseñanza del español con percusión o piano en {}",
    "clases de español en {} integrando música latinoamericana",
    "español para niños con canciones en {} comunidad hispana",
    "centros educativos que integran música y español en {}",
    '"Spanish through music" {} site:eventbrite.com',
    '"Learn Spanish with music" {} Australia',
    "programas de español para niños en {} con enfoque musical",
    "enseñanza del español a través del canto en {}",
    "talleres de español cantado en {} junio 2025",
    "espacios latinos en {} que combinan música y lengua",
    "academias de español con actividades musicales en {}",
    "enseñar español a través de la música en {} comunidad latina",
    "escuelas latinas en {} que enseñan español con canciones",
    "actividades musicales para aprender español en {} para migrantes",
    "eventos para aprender español con ritmo en {} mayo junio 2025",
    "método musical para enseñar español en {} academias culturales",
    "taller de integración social con música en español en {}",
    "actividades comunitarias con canto y percusión en {} comunidad hispana",
    "centro de apoyo hispano en {} con talleres musicales recientes",
    "grupo de integración cultural usando música latina en {}",
    "colectivo hispano en {} que organiza talleres de música comunitaria",
    "música para integración cultural en español en {} 2025",
    "percusión colectiva como herramienta de integración en {} comunidad latina",
    "asociaciones latinas en {} con programas de integración musical",
    '"Spanish community music workshop" {} Australia',
    "canto grupal en español como integración social en {}",
    "talleres culturales con música en español {} comunidad migrante",
    "programas de cohesión social con música en {} para latinos",
    "eventos para integración de hispanohablantes con música en {}",
    "centros culturales latinos en {} actividades de percusión grupal",
    "usando el piano o canto para integrar migrantes en {} comunidad hispana",
    "iniciativas de integración comunitaria con música en español en {}",
    "música colaborativa como puente cultural en {} comunidad latina",
    "asociaciones de migrantes hispanos en {} con talleres musicales recientes",
    "programas de integración para nuevos migrantes hispanos en {} con música",
    "eventos inclusivos con canto y ritmo en español en {} junio 2025",
    "organizaciones latinas en {} que participaron en festivales culturales 2025",
    "festival cultural latino en {} con talleres musicales en español",
    "eventos recientes en {} con participación de colectivos hispanohablantes y música en vivo",
    "taller de canto o percusión en festival latino en {} comunidad hispana",
    "asociaciones latinas en {} que ofrecieron workshops musicales en festivales",
    "grupos culturales latinos en {} música en vivo y talleres en eventos",
    "participación hispana en festivales musicales multiculturales en {}",
    '"Latin cultural festival" {} with music workshops',
    "danza y percusión en vivo en eventos latinos en {} junio 2025",
    "colectivos musicales hispanos en {} en festivales culturales recientes",
    "talleres de música latina en español ofrecidos en festivales de {}",
    "organizaciones culturales hispanas en {} eventos musicales recientes",
    "festival latino en {} con clases de canto o ritmo en español",
    "actividades musicales en español durante eventos culturales en {}",
    "festivales multiculturales en {} con presencia hispana y música en vivo",
    "workshop de música tradicional latina en {} festival comunitario",
    "Adelaida asociaciones hispanas música talleres eventos culturales",
    "talleres rítmicos y danzas con música en vivo en {} eventos latinos",
    "festival cultural latinoamericano en {} con canto, percusión o piano",
    "eventos de integración cultural con talleres musicales latinos en {}"
]

LIMITE_POR_CIUDAD = 1000

HEADERS = {
    'X-API-KEY': API_KEY,
    'Content-Type': 'application/json'
}

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Linux; Android 13; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.90 Mobile Safari/537.36"
]
