from datetime import datetime
import os

# API_KEY = "d610c594d99e9914f73ea072d3904a8758f107cb"
API_KEY = os.getenv("SERPER_API_KEY")

CIUDADES = [
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast", "Hobart",
    "Auckland", "Wellington", "Christchurch",
    "Tokyo", "Osaka", "Kyoto",
    "Seúl", "Busan",
    "Manila", "Cebu",
    "Kuala Lumpur", "George Town",
    "Singapur",
    "Bangkok", "Chiang Mai"
]

# Lista base unificada con marcador {ciudad} para insertar la ciudad dinámica
PROMPTS_ROTATIVOS = [
    "organización latina en {} con actividad infantil 2025",
    "grupo de apoyo migrante hispano en {} con evento comunitario 2024",
    "colectivo latino en {} con jornada cultural 2024",
    "grupo comunitario hispanohablante en {} con programa de integración 2024",
    "asociación de residentes hispanohablantes en {} con espacio cultural 2025",
    "grupo vecinal en español en {} con actividad recreativa 2024",
    "red comunitaria en español en {} con actividad familiar 2025",
    "grupo barrial hispano en {} con actividad cultural 2024",
    "colectivo social hispano en {} con intercambio cultural 2025",
    "grupo de familias hispanas en {} con jornada cultural 2024",
    "grupo de integración cultural hispano en {} con actividad recreativa 2025",
    "colectivo de migrantes en {} con evento comunitario 2025",
    "organización hispanohablante en {} con taller vecinal 2024",
    "grupo cultural hispano en {} con actividades familiares 2024",
    "comunidad latina en {} con actividades sociales recientes",
    "grupo hispano en {} con encuentro de familias 2025",
    "asociación de apoyo a migrantes en {} con actividades 2025",
    "colectivo comunitario en {} con evento cultural reciente",
    "grupo vecinal hispano en {} con integración de familias migrantes",
    "organización de hispanohablantes en {} con actividad recreativa",
    "asociación cultural en español en {} con evento para familias",
    "grupo de integración para hispanos en {} con actividades recientes",
    "grupo de barrio hispano en {} con espacio comunitario",
    "colectivo de familias latinas en {} con evento al aire libre",
    "grupo de vecinos hispanohablantes en {} con reunión comunitaria",
    "comunidad hispana en {} con programa de integración social",
    "organización barrial en {} para familias hispanas migrantes",
    "asociación comunitaria hispana en {} con actividad familiar 2025",
    "grupo de padres hispanohablantes en {} con actividades sociales",
    "colectivo de integración hispana en {} con taller cultural",
    "grupo social de migrantes latinos en {} con reunión cultural",
    "comunidad de habla hispana en {} con eventos 2025",
    "grupo comunitario en español en {} con integración de migrantes",
    "asociación de vecinos latinos en {} con eventos recientes",
    "grupo cultural de migrantes hispanos en {} con actividades infantiles",
    "red de familias hispanas en {} con talleres comunitarios",
    "grupo local de hispanos en {} con actividades colaborativas",
    "grupo comunitario en español en {} con programas para niños",
    "colectivo de vecinos hispanos en {} con actividades 2025",
    "grupo barrial de hispanohablantes en {} con programa social",
    "organización vecinal latina en {} con actividades recientes",
    "grupo familiar hispano en {} con actividades sin fines de lucro",
    "asociación de integración comunitaria en {} para latinos",
    "colectivo familiar en {} con enfoque cultural hispano",
    "grupo solidario hispano en {} con encuentros vecinales",
    "asociación de migrantes hispanos en {} con talleres abiertos",
    "grupo social hispano en {} con eventos inclusivos",
    "grupo de vecinas latinas en {} con jornadas de integración",
    "asociación barrial de habla hispana en {} con actividades comunitarias",
    "grupo hispano local en {} con agenda comunitaria 2025",
    "colectivo comunitario de hispanohablantes en {} con eventos",
    "grupo de madres y padres latinos en {} con apoyo vecinal",
    "grupo comunitario de integración en {} con enfoque en familias hispanas",
    "organización social en español en {} con evento local reciente",
    "grupo de apoyo familiar hispano en {} con actividad cultural",
    "asociación hispana en {} con proyectos sociales activos",
    "red comunitaria en {} con enfoque en migrantes hispanohablantes",
    "grupo vecinal latino en {} con acciones sociales 2025",
    "asociación de apoyo social en español en {} con programas inclusivos",
    "colectivo de integración en español en {} con actividades barriales",
    "grupo de residentes latinos en {} con participación ciudadana",
    "colectivo cultural en español en {} con actividades abiertas",
    "asociación de padres hispanos en {} con programas recreativos",
    "grupo colaborativo en español en {} con agenda local 2025",
    "asociación de la comunidad hispana en {} con eventos de integración",
    "grupo vecinal en español en {} con actividades culturales",
    "asociación social en {} con enfoque en familias hispanohablantes",
    "organización de migrantes hispanos en {} con eventos colaborativos",
    "grupo de acción comunitaria en español en {} con participación vecinal",
    "grupo de ciudadanos latinos en {} con encuentro familiar",
    "organización social latina en {} con enfoque en comunidad barrial",
    "grupo comunitario en español en {} con jornada inclusiva",
    "colectivo cultural de migrantes latinos en {} con eventos familiares",
    "asociación local en español en {} con actividades intergeneracionales",
    "grupo barrial de habla hispana en {} con jornadas culturales",
    "grupo de integración social en español en {} con enfoque migrante",
    "asociación de vecinas latinas en {} con enfoque en la niñez",
    "organización sin fines de lucro en español en {} con acciones comunitarias",
    "grupo de barrio hispanohablante en {} con programas sociales",
    "red de apoyo hispano en {} con actividades de inclusión",
    "grupo de participación vecinal en español en {} con enfoque cultural",
    "asociación de familias migrantes en {} con enfoque comunitario",
    "colectivo latinoamericano en {} con actividades sociales recientes",
    "organización barrial de hispanohablantes en {} con eventos 2025",
    "grupo local hispano en {} con actividades abiertas a la comunidad",
    "grupo de encuentro cultural en español en {} con participación ciudadana",
    "organización comunitaria en español en {} con eventos sin fines de lucro",
    "colectivo de inclusión para familias hispanas en {} con actividades sociales",
    "asociación de residentes latinos en {} con jornadas vecinales",
    "grupo vecinal colaborativo en español en {} con eventos recientes",
    "organización de familias hispanas migrantes en {} con integración comunitaria",
    "grupo de apoyo latino en {} con participación barrial 2025",
    "asociación social latina en {} con talleres familiares",
    "grupo cultural local en español en {} con actividades gratuitas",
    "grupo de inclusión social en español en {} con enfoque en infancia",
    "asociación de barrio en {} con comunidad hispana activa",
    "colectivo social latino en {} con actividades para migrantes"
]

LIMITE_POR_CIUDAD = 200

HEADERS = {
    'X-API-KEY': API_KEY,
    'Content-Type': 'application/json'
}

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Linux; Android 13; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.90 Mobile Safari/537.36"
]
