name: Ejecutar Scraper 5 veces al día

on:
  schedule:
    - cron: '0 6 * * *'   # 09:00 UTC
    - cron: '0 8 * * *'  # 12:00 UTC
    - cron: '0 10 * * *'  # 12:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 14 * * *'  # 12:00 UTC
    - cron: '0 16 * * *'  # 12:00 UTC
  workflow_dispatch:      # Permitir ejecución manual desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Se actualiza a 3.10

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar scraper
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
      run: python main.py
