name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecutar todos los días a las 12:00 UTC
  workflow_dispatch:      # Permitir ejecución manual desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar scraper
      env:
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
      run: python main.py
